[overlay]
# Прозрачность HUD. Большое значение делает интерфейс более заметным. Малое значение делает интерфейс почти прозрачным. Слишком высокий HUD мешает обзору кадра. Подбирайте под яркость сцены и дисплей.
HUD_ALPHA = 0.25

# Размер красного крестика у цели (пиксели).
TARGETING_CROSS_SIZE = 7
